//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatSprirtProm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int id_delivery { get; set; }
        public System.DateTime data_delivery { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_storage { get; set; }
        public Nullable<int> count { get; set; }
        public string comment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
