//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatSprirtProm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_order { get; set; }
        public System.DateTime data_order { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> count { get; set; }
        public string comment { get; set; }
        public Nullable<int> id_organization { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Product Product { get; set; }
    }
}
